### ISSUE TITLE
php7 branch: SegFault when calling ->connect() 

### ISSUE THREAD

**Issue by justwakku** [mgdm/Mosquitto-PHP#38]
Hi, we are getting SegFault signal and the backtrace from gdb says:

```
Program terminated with signal 11, Segmentation fault.
#0  zend_vm_stack_push_call_frame_ex (execute_data=0x7f6c02013030) at /usr/src/php-7.0.6/Zend/zend_execute.h:181
181                     ZEND_SET_CALL_INFO(call, call_info);
```

Here is backtrace:

```
#8  0x00000000007e3216 in main (argc=2, argv=0x1d8aa30) at /usr/src/php-7.0.6/sapi/cli/php_cli.c:1344
1344                            exit_status = do_cli(argc, argv);
#7  0x00000000007e2a9e in do_cli (argc=2, argv=0x1d8aa30) at /usr/src/php-7.0.6/sapi/cli/php_cli.c:974
974                                     php_execute_script(&file_handle);
#6  0x00000000006f3b98 in php_execute_script (primary_file=0x7ffe154f3a50) at /usr/src/php-7.0.6/main/main.c:2494
2494                            retval = (zend_execute_scripts(ZEND_REQUIRE, NULL, 3, prepend_file_p, primary_file, append_file_p) == SUCCESS);
#5  0x000000000074f8d7 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /usr/src/php-7.0.6/Zend/zend.c:1427
1427                            zend_execute(op_array, retval);
#4  0x00000000007de9f3 in zend_execute (op_array=0x7f6c0207d000, return_value=<value optimized out>) at /usr/src/php-7.0.6/Zend/zend_vm_execute.h:458
458             zend_execute_ex(execute_data);
#3  0x000000000078de40 in execute_ex (ex=<value optimized out>) at /usr/src/php-7.0.6/Zend/zend_vm_execute.h:417
417                     if (UNEXPECTED((ret = ((opcode_handler_t)OPLINE->handler)(ZEND_OPCODE_HANDLER_ARGS_PASSTHRU)) != 0))                                                                                         {
#2  ZEND_INIT_METHOD_CALL_SPEC_CV_CONST_HANDLER (execute_data=0x7f6c02013030) at /usr/src/php-7.0.6/Zend/zend_vm_execute.h:32123
32123           call = zend_vm_stack_push_call_frame(call_info,
#1  zend_vm_stack_push_call_frame (execute_data=0x7f6c02013030) at /usr/src/php-7.0.6/Zend/zend_execute.h:207
207             return zend_vm_stack_push_call_frame_ex(used_stack, call_info,
#0  zend_vm_stack_push_call_frame_ex (execute_data=0x7f6c02013030) at /usr/src/php-7.0.6/Zend/zend_execute.h:181
181                     ZEND_SET_CALL_INFO(call, call_info);

```

**Comment by mgdm** [comment]
Yes, it's not finished yet.

**Comment by justwakku** [comment]
@mgdm oh, i see. sorry to bother u. XD

**Comment by gjongenelen** [comment]
Is there any ETA of this release?

**Comment by mgdm** [comment]
Not currently. I'm working on it when I get spare time.
