### ISSUE TITLE
New PHP 7 SegFault

### ISSUE THREAD

**Issue by davidg246819** [mgdm/Mosquitto-PHP#59]
This segfaults on PHP 7.0.12 (default php.ini) with Mosquitto-PHP master on second publish to /ping/test with payload of "1"
```
<?php
function print_nl($x) { print $x.PHP_EOL; }
$SUB = new Mosquitto\Client(uniqid(), false);
$SUB->setCredentials("user", "pass");
$SUB->connect("127.0.0.1", 1883);
$SUB->subscribe("/ping/test", 0);
$SUB->onMessage(function($message) {
 print_nl(memory_get_usage());
 print_r($message);
 print_nl("Received PING from from worker monitor. Performing worker checks...");
});
while(true) {
 try { $SUB->loop(5); } catch(Exception $e) { print_nl("Caught exception."); }
}
```
Changing to
```print_nl("Received PING from from worker monitor.");```
does not

```
(gdb) run test.php
Starting program: /usr/bin/php test.php
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
1221744
Mosquitto\Message Object
(
    [mid] => 0
    [topic] => /ping/test
    [payload] => 1
    [qos] => 0
    [retain] => 
)
Received PING from from worker monitor. Performing worker checks...
1221680
Mosquitto\Message Object
(
    [mid] => 0
    [topic] => /ping/test
    [payload] => 1
    [qos] => 0
    [retain] => 
)
Received PING from from worker monitor. Performing worker checks...

Program received signal SIGSEGV, Segmentation fault.
0x00005555557f3fcb in zend_objects_store_del ()
(gdb) bt
#0  0x00005555557f3fcb in zend_objects_store_del ()
#1  0x00007ffff161695d in php_mosquitto_message_callback (mosq=<optimized out>, client_obj=0x7ffff5f44500, message=0x555555d9a0a8) at /usr/src/Mosquitto-PHP/mosquitto.c:1171
#2  0x00007ffff1409465 in ?? () from /usr/lib/x86_64-linux-gnu/libmosquitto.so.1
#3  0x00007ffff14088e6 in ?? () from /usr/lib/x86_64-linux-gnu/libmosquitto.so.1
#4  0x00007ffff1406105 in mosquitto_loop_read () from /usr/lib/x86_64-linux-gnu/libmosquitto.so.1
#5  0x00007ffff1406530 in ?? () from /usr/lib/x86_64-linux-gnu/libmosquitto.so.1
#6  0x00007ffff161890a in zim_Mosquitto_Client_loop (execute_data=0x7ffff5e13160, return_value=<optimized out>) at /usr/src/Mosquitto-PHP/mosquitto.c:777
#7  0x00005555557a795a in dtrace_execute_internal ()
#8  0x000055555583ca90 in ?? ()
#9  0x00005555557f7e1b in execute_ex ()
#10 0x00005555557a77e8 in dtrace_execute_ex ()
#11 0x000055555584c8e7 in zend_execute ()
#12 0x00005555557b7b63 in zend_execute_scripts ()
#13 0x0000555555757f1b in php_execute_script ()
#14 0x000055555584e59a in ?? ()
#15 0x000055555563cfed in main ()
```

I don't know enough about Zend to track this down. Anyone have any ideas?

Also, any idea why is mid always 0?

**Comment by mgdm** [comment]
I'll have a look into the segfault.

Someone else has mentioned the mid always being zero, I need to look further into that too. I thought it was maybe that the broker wasn't assigning one if it was QoS 0, but I need to test that.

**Comment by davidg246819** [comment]
Just tried with QoS 1 on sub and pub. The mid increases, segfault still occurs.

**Comment by argakon** [comment]
Probably this segfault is my fault. I tested my previous pull request on mips router under php 7.0.12 and all works fine and i didn't saw mistake, strange thing... Now i tested all under ubuntu 14.04 php 7.0.12 and created new pull [request](https://github.com/mgdm/Mosquitto-PHP/pull/60)

**Comment by davidg246819** [comment]
With PR #60 the above script seems to work fine now.
